// <auto-generated />
namespace BohFoundation.EntityFrameworkBaseClass.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class FinalizedButNotCompletedApplicant : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FinalizedButNotCompletedApplicant));
        
        string IMigrationMetadata.Id
        {
            get { return "201409091411442_FinalizedButNotCompletedApplicant"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
