// <auto-generated />
namespace BohFoundation.EntityFrameworkBaseClass.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AddedBoolsToIndicateIfTranscriptsAndW2sWereUploaded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedBoolsToIndicateIfTranscriptsAndW2sWereUploaded));
        
        string IMigrationMetadata.Id
        {
            get { return "201407021610369_AddedBoolsToIndicateIfTranscriptsAndW2sWereUploaded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
