// <auto-generated />
namespace BohFoundation.EntityFrameworkBaseClass.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class SeperatingOutW2AndTranscriptIntoOwnEntities : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SeperatingOutW2AndTranscriptIntoOwnEntities));
        
        string IMigrationMetadata.Id
        {
            get { return "201407031131380_SeperatingOutW2AndTranscriptIntoOwnEntities"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
